name: Publish

on:
  push:
    branches: [ main ]

env:
  DOTNET_VERSION: '6.0.*'

jobs:
  publish:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: |
        dotnet build --configuration Release --no-restore
        dotnet publish -c Release -o ../afkparser -r win-x64 --self-contained false /p:UseAppHost=true
      
    - name: Package release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'afkparser.zip'
        path: bin\Release\net6.0\win-x64
      
    - name: Publish
      uses: ncipollo/release-action@v1
      with:
        artifacts: 'afkparser.zip'
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: Continuous
